-- Align diagram_type enum to 13 UML + 4 C4 types
CREATE TYPE "diagram_type_new" AS ENUM (
  'CLASS',
  'PACKAGE',
  'OBJECT',
  'COMPONENT',
  'DEPLOYMENT',
  'COMPOSITE_STRUCTURE',
  'ACTIVITY',
  'SEQUENCE',
  'COMMUNICATION',
  'INTERACTION_OVERVIEW',
  'TIMING',
  'USE_CASE',
  'STATE',
  'C4_CONTEXT',
  'C4_CONTAINER',
  'C4_COMPONENT',
  'C4_CODE'
);

ALTER TABLE "Diagrams" ALTER COLUMN "type" TYPE "diagram_type_new" USING (
  CASE "type"::text
    WHEN 'C4_DYNAMIC' THEN 'C4_CODE'
    WHEN 'C4_DEPLOYMENT' THEN 'C4_CODE'
    WHEN 'FLOWCHART' THEN 'ACTIVITY'
    WHEN 'ENTITY_RELATIONSHIP' THEN 'CLASS'
    WHEN 'USER_JOURNEY' THEN 'USE_CASE'
    WHEN 'GANTT' THEN 'TIMING'
    WHEN 'PIE_CHART' THEN 'CLASS'
    WHEN 'QUADRANT_CHART' THEN 'CLASS'
    WHEN 'REQUIREMENT' THEN 'USE_CASE'
    WHEN 'GITGRAPH' THEN 'SEQUENCE'
    WHEN 'MINDMAP' THEN 'COMPOSITE_STRUCTURE'
    WHEN 'TIMELINE' THEN 'SEQUENCE'
    WHEN 'SANKEY' THEN 'ACTIVITY'
    ELSE "type"::text
  END
)::"diagram_type_new";

DROP TYPE "diagram_type";
ALTER TYPE "diagram_type_new" RENAME TO "diagram_type";
